[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "mudssky", email = "mudssky@gmail.com"},
]
dependencies = [
    "pymongo>=4.3.3",
    "fire>=0.5.0",
    "pyquery>=2.0.0",
    "requests>=2.28.2",
]
requires-python = ">=3.11"
license = {text = "MIT"}
